[package]
name = "tinymvt"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Simple library for serializing Mapbox Vector Tile (MVT) with minimal dependencies."

[dependencies]
ahash = "0.8.11"
indexmap = "2.6.0"
prost = "0.13.3"

[build-dependencies]
prost-build = "0.13.3"
